"""initial_models

Revision ID: d42085505b78
Revises: 
Create Date: 2026-02-25 03:07:30.893807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42085505b78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_sites_user_id'), ['user_id'], unique=False)

    op.create_table('daily_browser_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('browser', sa.String(length=64), nullable=False),
    sa.Column('pageviews', sa.Integer(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'date', 'browser', name='uq_daily_browser')
    )
    with op.batch_alter_table('daily_browser_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_browser_stats_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_browser_stats_site_id'), ['site_id'], unique=False)

    op.create_table('daily_country_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('pageviews', sa.Integer(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'date', 'country_code', name='uq_daily_country')
    )
    with op.batch_alter_table('daily_country_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_country_stats_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_country_stats_site_id'), ['site_id'], unique=False)

    op.create_table('daily_device_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('device_type', sa.String(length=16), nullable=False),
    sa.Column('pageviews', sa.Integer(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'date', 'device_type', name='uq_daily_device')
    )
    with op.batch_alter_table('daily_device_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_device_stats_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_device_stats_site_id'), ['site_id'], unique=False)

    op.create_table('daily_page_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('pageviews', sa.Integer(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'date', 'path', name='uq_daily_page')
    )
    with op.batch_alter_table('daily_page_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_page_stats_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_page_stats_site_id'), ['site_id'], unique=False)

    op.create_table('daily_referrer_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('referrer_domain', sa.String(length=255), nullable=False),
    sa.Column('pageviews', sa.Integer(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'date', 'referrer_domain', name='uq_daily_referrer')
    )
    with op.batch_alter_table('daily_referrer_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_referrer_stats_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_referrer_stats_site_id'), ['site_id'], unique=False)

    op.create_table('daily_utm_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('utm_source', sa.String(length=255), nullable=False),
    sa.Column('utm_medium', sa.String(length=255), nullable=False),
    sa.Column('utm_campaign', sa.String(length=255), nullable=False),
    sa.Column('pageviews', sa.Integer(), nullable=False),
    sa.Column('unique_visitors', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'date', 'utm_source', 'utm_medium', 'utm_campaign', name='uq_daily_utm')
    )
    with op.batch_alter_table('daily_utm_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_utm_stats_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_utm_stats_site_id'), ['site_id'], unique=False)

    op.create_table('pageview_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('visitor_hash', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('referrer', sa.String(length=2048), nullable=True),
    sa.Column('referrer_domain', sa.String(length=255), nullable=True),
    sa.Column('browser', sa.String(length=64), nullable=True),
    sa.Column('os', sa.String(length=64), nullable=True),
    sa.Column('device_type', sa.String(length=16), nullable=True),
    sa.Column('screen_width', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('utm_source', sa.String(length=255), nullable=True),
    sa.Column('utm_medium', sa.String(length=255), nullable=True),
    sa.Column('utm_campaign', sa.String(length=255), nullable=True),
    sa.Column('utm_term', sa.String(length=255), nullable=True),
    sa.Column('utm_content', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pageview_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pageview_events_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_pageview_events_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pageview_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_pageview_events_visitor_hash'), ['visitor_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pageview_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pageview_events_visitor_hash'))
        batch_op.drop_index(batch_op.f('ix_pageview_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_pageview_events_site_id'))
        batch_op.drop_index(batch_op.f('ix_pageview_events_path'))

    op.drop_table('pageview_events')
    with op.batch_alter_table('daily_utm_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_utm_stats_site_id'))
        batch_op.drop_index(batch_op.f('ix_daily_utm_stats_date'))

    op.drop_table('daily_utm_stats')
    with op.batch_alter_table('daily_referrer_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_referrer_stats_site_id'))
        batch_op.drop_index(batch_op.f('ix_daily_referrer_stats_date'))

    op.drop_table('daily_referrer_stats')
    with op.batch_alter_table('daily_page_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_page_stats_site_id'))
        batch_op.drop_index(batch_op.f('ix_daily_page_stats_date'))

    op.drop_table('daily_page_stats')
    with op.batch_alter_table('daily_device_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_device_stats_site_id'))
        batch_op.drop_index(batch_op.f('ix_daily_device_stats_date'))

    op.drop_table('daily_device_stats')
    with op.batch_alter_table('daily_country_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_country_stats_site_id'))
        batch_op.drop_index(batch_op.f('ix_daily_country_stats_date'))

    op.drop_table('daily_country_stats')
    with op.batch_alter_table('daily_browser_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_browser_stats_site_id'))
        batch_op.drop_index(batch_op.f('ix_daily_browser_stats_date'))

    op.drop_table('daily_browser_stats')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_user_id'))
        batch_op.drop_index(batch_op.f('ix_sites_domain'))

    op.drop_table('sites')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
